# Generated by Django 4.1.7 on 2023-04-01 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_cart_order_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='prouser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Order received', 'Order received'), ('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Order received', max_length=50),
        ),
    ]
