# Generated by Django 4.1.7 on 2023-04-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_order_status_alter_profile_prouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order received', 'Order received'), ('Order Completed', 'Order Completed')], default='Order received', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='userprofile.png', null=True, upload_to='profile/'),
        ),
    ]
