# Generated by Django 4.1.7 on 2023-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_order_status_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order received', 'Order received'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing')], default='Order received', max_length=50),
        ),
    ]
