# Generated by Django 4.1.7 on 2023-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order received', 'Order received'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('On the way', 'On the way')], default='Order received', max_length=50),
        ),
    ]
