# Generated by Django 4.1.7 on 2023-07-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order received', 'Order received'), ('Order Processing', 'Order Processing')], default='Order received', max_length=50),
        ),
    ]
