# Generated by Django 4.1.7 on 2023-07-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('On the way', 'On the way'), ('Order received', 'Order received'), ('Order Canceled', 'Order Canceled')], default='Order received', max_length=50),
        ),
    ]
